stages:
  prepare_data:
    cmd: python src/config/prepare_data.py dados/credicard.csv.gz dados/credicard_tratado.parquet
    deps:
    - dados/credicard.csv.gz
    outs:
    - dados/credicard_tratado.parquet

  train_model:
    cmd: python src/config/train_model.py
    deps:
    - dados/credicard_tratado.parquet
    - src/config/train_model.py
    outs:
    - models/model.pkl
    metrics:
    - metrics.json

  generate_shap_insights:
    cmd: python src/config/generate_shap_insights.py
    deps:
      - src/config/generate_shap_insights.py
      - models/model.pkl
      - dados/credicard_tratado.parquet
    outs:
      - reports/shap_explanations:
          persist: true

  generate_shap_report:
    cmd: python src/config/generate_shap_report.py
    deps:
      - src/config/generate_shap_report.py
      - reports/shap_explanations/
    outs:
      - reports/shap_report.pdf
